name: Health Check
on:
  schedule:
    - cron: '0/10 * * * *'
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/healthcheck.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Health Check
        uses: ./
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          command: health-check
