name: Health Check on Course Plan
on:
  schedule:
    - cron: '0/10 * * * *'
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/healthcheck.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Health Check
        uses: ./
        with:
          command: health-check
