name: Health Check on Course Plan
on:
  schedule:
    - cron: '0/10 * * * *'
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/healthcheck-course-plan.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Yarn Install
        run: yarn install
      - name: Health Check
        run: yarn health-check https://courseplan.io/
