name: Health Check on Research Connect
on:
  schedule:
    - cron: '0/10 * * * *'
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/healthcheck-research-connect.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Yarn Install
        run: yarn install
      - name: Health Check
        run: yarn health-check https://www.research-connect.com/
