name: Health Check on CUReviews
on:
  schedule:
    - cron: '0/30 * * * *'
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/healthcheck-cureviews.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Yarn Install
        run: yarn install
      - name: Health Check
        run: yarn health-check https://www.cureviews.org/
