name: Merge Policies
on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Stale Branches Check
        uses: ./
        with:
          command: merge-policies
