name: Merge Policies
on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Merge Policies Check
        uses: ./
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          command: merge-policies
