name: Write Checks
on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Write Dummy Pending Check
        uses: ./
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          command: write-status
          argument: 'true Pending Status'
      - name: Write Dummy Successful Status
        uses: ./
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          command: write-status
          argument: 'false Successful Status'
